### ISSUE TITLE
SIGSEGV crash due to bad pointer dereference.

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/ndt-server#153]
First observed on bom02 due to a very high container restart rate. Some evidence on other nodes but at much less frequency. This could be the result of client populations.

```
98.160.171.234 - - [19/Jul/2019:07:56:21 +0000] "GET /ndt_protocol HTTP/1.1" 200 0
2019/07/19 07:56:31 ndt5.go:118: Handling connection 63.243.240.101:3010<=WS(S),JSON=>98.160.171.234:47570
2019/07/19 07:56:34 server.go:3012: http: TLS handshake error from [2600:3c02::17:d804]:47730: EOF
2019/07/19 07:56:37 web100_linux.go:24: Summarized data: &{0 14 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0}
2019/07/19 07:56:39 protocol.go:274: Connection is not a TCPConn
2019/07/19 07:56:39 ndt5.go:64: Wrote /var/spool/ndt/ndt5/2019/07/19/ndt-vdzbg_1563218806_00000000000044FE.json
2019/07/19 07:56:39 ndt5.go:104: Test failed, but we recovered: runtime error: invalid memory address or nil pointer dereference
2019/07/19 07:56:39 close.go:31: Could not close connection (close tcp 63.243.240.101:3001->195.206.104.52:35898: use of closed network connection)
2019/07/19 07:56:41 c2s.go:99: Ended C2S test on 63.243.240.101:43435<=WS(S),JSON=>98.160.171.234:46416
2019/07/19 07:56:41 c2s.go:119: 63.243.240.101:3010<=WS(S),JSON=>98.160.171.234:47570 sent us 5242.633287687231 Kbps
2019/07/19 07:56:41 ndt5.go:216: You uploaded at 5242.6333 and downloaded at 0.0000
2019/07/19 07:56:41 ndt5.go:64: Wrote /var/spool/ndt/ndt5/2019/07/19/ndt-vdzbg_1563218806_0000000000004507.json
2019/07/19 07:56:41 close.go:31: Could not close connection (tls: use of closed connection)
98.160.171.234 - - [19/Jul/2019:07:56:31 +0000] "GET /ndt_protocol HTTP/1.1" 200 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x82d8f2]

goroutine 12245 [running]:
github.com/m-lab/ndt-server/ndt5/protocol.(*netConnection).Close(0xc0001b2550, 0x9701f8, 0xd830a0)
        <autogenerated>:1 +0x32
github.com/m-lab/go/warnonerror.Close(0x7f5759bbdfb8, 0xc0001b2550, 0x95af09, 0x1f, 0xc0001b2550, 0x45ccc6)
        /go/src/github.com/m-lab/go/warnonerror/close.go:29 +0x35
github.com/m-lab/ndt-server/ndt5/c2s.ManageTest.func2.1(0x7f5759bbdfd8, 0xc0001b2550)
        /go/src/github.com/m-lab/ndt-server/ndt5/c2s/c2s.go:80 +0x7c
created by github.com/m-lab/ndt-server/ndt5/c2s.ManageTest.func2
        /go/src/github.com/m-lab/ndt-server/ndt5/c2s/c2s.go:78 +0x49
```

**Comment by stephen-soltesz** [comment]
I believe the following sequence is happening:

• a plain server `ServeOnce()` returns a bad testConn
• a goroutine with 3sec timer to close bad testConn on c2s.ManageTest return is defer'd
• ServerIPAndPort() panics b/c the testConn is invalid (or testConn.LocalAddr() is not a *net.TCPAddr)
• first panic recovery happens in HandleControlChannel, defer'd close runs
• after 3 more seconds the defer'd sleep returns and attempts testConn.Close, which also generates a panic b/c testConn is invalid, and crashes the server.

Why or how is `ServeOnce` returning n invalid testConn? At least one case is when the ServeOnce ctx times out (>30sec).

https://github.com/m-lab/ndt-server/blob/655fc0954a59a7633841aa7460e8901d91417e77/ndt5/singleserving/server.go#L185-L190

B/c Accept never returned, `err == nil`, and for the same reason `conn` is also nil.

**Comment by stephen-soltesz** [comment]
Reproducible by connecting to server and never running C2S test:

```
	fmt.Println("Connecting")
	d := net.Dialer{Timeout: time.Second}
	v, err := d.Dial("tcp", "127.0.0.1:3001")
	rtx.Must(err, "Failed to connect")

	// Write initial TLV with <MsgLogin (2)><2-byte length: 0,1><TestStatus | TestC2S (16 | 2)>
	v.Write([]byte{2, 0, 1, 18})

	// Expect the "kickoff" string -- "123456 654321"
	b := make([]byte, 100)
	v.Read(b)

	log.Println(string(b))
	time.Sleep(60 * time.Second)
```
